Fix starter kits not applied on first join
Starter kits not applied when joining server for the first time due to
silent failure of KitDataLoadEvent.

  java.lang.IllegalStateException: KitDataLoadEvent may only be triggered synchronously.

- Make KitDataLoadEvent able to run async with super(true).
- Determine first join before async task to prevent race condition where
  the player appears to have already joined.